housing_market:
  outputs:
    dev:
      type: duckdb
      path: dev.db
      threads: 2

    prod:
      type: snowflake
      account: 'snowflake_path_here'
      keyfile: 'path_to_config_file'

      user: galavera
      password: ####

      database:
      schema:
      threads: 2
      client_session_keep_alive: False

  target: dev
