version: 2

models:
  - name: raw_data
    description: "Weekly statistics for the housing market"
  - name: processed_data
    description: "Processed data for the housing market"
  - name: f_housing_market
    description: "Housing Market fact table"
